-- MySQL Script generated by MySQL Workbench
-- Qua 19 Abr 2017 07:36:36 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema creas_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema creas_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `creas_db` DEFAULT CHARACTER SET latin1 ;
USE `creas_db` ;

-- -----------------------------------------------------
-- Table `creas_db`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`cargo` (
  `idCargo` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `descricao` TEXT NULL DEFAULT NULL COMMENT '',
  `nivel` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idCargo`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `creas_db`.`setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`setor` (
  `id_setor` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id_setor`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `creas_db`.`tipo_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tipo_pessoa` (
  `id_tipo_pessoa` INT NOT NULL COMMENT '',
  `nome_tipo_pessoa` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_tipo_pessoa`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_tipo_certidao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_tipo_certidao` (
  `id_tipo_certidao` INT NOT NULL COMMENT '',
  `descricao_tipo` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_tipo_certidao`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`documentos_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`documentos_pessoa` (
  `id_documentos` INT NOT NULL COMMENT '',
  `id_tipo_certidao` INT NULL COMMENT '',
  `num_certidao` BIGINT NULL COMMENT '',
  `num_livro` INT NULL COMMENT '',
  `num_folhas` INT NULL COMMENT '',
  `cpf` BIGINT NULL COMMENT '',
  `titulo_eleitor` BIGINT NULL COMMENT '',
  `zona_eleitor` INT NULL COMMENT '',
  `sessao_eleitor` TEXT NULL COMMENT '',
  `rg` BIGINT NULL COMMENT '',
  `compl_rg` TEXT NULL COMMENT '',
  `data_emissao` DATE NULL COMMENT '',
  `orgao_emissor` TEXT NULL COMMENT '',
  `ctps` BIGINT NULL COMMENT '',
  `serie_ctps` INT NULL COMMENT '',
  `data_emiss_ctps` DATE NULL COMMENT '',
  `nis` BIGINT NULL COMMENT '',
  `cam` TEXT NULL COMMENT '',
  `rne` TEXT NULL COMMENT '',
  `tb_tipo_certidao_id_tipo_certidao` INT NOT NULL COMMENT '',
  `tb_tipo_certidao_id_tipo_certidao1` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_documentos`)  COMMENT '',
  INDEX `fk_documentos_tb_tipo_certidao1_idx` (`tb_tipo_certidao_id_tipo_certidao1` ASC, `id_tipo_certidao` ASC)  COMMENT '',
  CONSTRAINT `id_tipo_certidao`
    FOREIGN KEY (`tb_tipo_certidao_id_tipo_certidao1` , `id_tipo_certidao`)
    REFERENCES `creas_db`.`tb_tipo_certidao` (`id_tipo_certidao` , `id_tipo_certidao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_escolaridade` (
  `id_escolaridade` INT NOT NULL COMMENT '',
  `desc_escolaridade` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_escolaridade`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_escola` (
  `id_escola` INT NOT NULL COMMENT '',
  `nome_escola` TEXT NULL COMMENT '',
  `tipo_escola` TEXT NULL COMMENT '',
  `uf_escola` TEXT NULL COMMENT '',
  `cidade_escola` TEXT NULL COMMENT '',
  `codigo_inep` BIGINT NULL COMMENT '',
  PRIMARY KEY (`id_escola`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_pessoa` (
  `id_pessoa` INT NOT NULL COMMENT '',
  `nome_pessoa` TEXT NULL COMMENT '',
  `id_tipo_pessoa` INT NOT NULL COMMENT '',
  `nome_social` TEXT NULL COMMENT '',
  `sexo` TEXT NULL COMMENT '',
  `data_nasc` DATE NULL COMMENT '',
  `idade` INT NULL COMMENT '',
  `estado_civil` TEXT NULL COMMENT '',
  `cor_raca` TEXT NULL COMMENT '',
  `uf_natal` TEXT NULL COMMENT '',
  `cidade_natal` TEXT NULL COMMENT '',
  `filhos` TINYINT(1) NULL COMMENT '',
  `qtde_filhos` INT NULL COMMENT '',
  `qtde_filhas` INT NULL COMMENT '',
  `id_documentos_pessoa` INT NOT NULL COMMENT '',
  `resp_unidade_familiar` TINYINT(1) NULL COMMENT '',
  `id_escolaridade` INT NULL COMMENT '',
  `ocupacao` TEXT NULL COMMENT '',
  `prog_TRM` TINYINT(1) NULL COMMENT '',
  `prog_acao_jovem` TINYINT(1) NULL COMMENT '',
  `prog_renda_cidada` TINYINT(1) NULL COMMENT '',
  `prog_sp_solidario` TINYINT(1) NULL COMMENT '',
  `prog_bolsa_familia` TINYINT(1) NULL COMMENT '',
  `prog_pro_jovem` TINYINT(1) NULL COMMENT '',
  `prog_peti` TINYINT(1) NULL COMMENT '',
  `prog_nenhum` TINYINT(1) NULL COMMENT '',
  `benef_bpc` TINYINT(1) NULL COMMENT '',
  `benef_vivaleite` TINYINT(1) NULL COMMENT '',
  `renda_familiar` REAL NULL COMMENT '',
  `renda_per_capta` REAL NULL COMMENT '',
  `aux_desemprego` TINYINT(1) NULL COMMENT '',
  `aux_maternidade` TINYINT(1) NULL COMMENT '',
  `aux_reclusao` TINYINT(1) NULL COMMENT '',
  `aux_aluguel` TINYINT(1) NULL COMMENT '',
  `aux_pensao` TINYINT(1) NULL COMMENT '',
  `sabe_ler` TINYINT(1) NULL COMMENT '',
  `sabe_escrever` TINYINT(1) NULL COMMENT '',
  `id_escola` INT NULL COMMENT '',
  `escola_eja` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id_pessoa`)  COMMENT '',
  INDEX `fk_tb_pessoa_tipo_pessoa1_idx` (`id_tipo_pessoa` ASC, `id_pessoa` ASC)  COMMENT '',
  INDEX `fk_tb_pessoa_documentos_pessoa1_idx` (`id_documentos_pessoa` ASC)  COMMENT '',
  INDEX `fk_tb_pessoa_escolaridade_idx` (`id_escolaridade` ASC)  COMMENT '',
  INDEX `fk_tb_pessoa_escola_idx` (`id_escola` ASC)  COMMENT '',
  CONSTRAINT `id_tipo_pessoa`
    FOREIGN KEY (`id_tipo_pessoa` , `id_pessoa`)
    REFERENCES `creas_db`.`tipo_pessoa` (`id_tipo_pessoa` , `id_tipo_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_documentos_pessoa`
    FOREIGN KEY (`id_documentos_pessoa`)
    REFERENCES `creas_db`.`documentos_pessoa` (`id_documentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pessoa_escolaridade`
    FOREIGN KEY (`id_escolaridade`)
    REFERENCES `creas_db`.`tb_escolaridade` (`id_escolaridade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pessoa_escola`
    FOREIGN KEY (`id_escola`)
    REFERENCES `creas_db`.`tb_escola` (`id_escola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(50) NOT NULL COMMENT '',
  `senha` VARCHAR(100) NOT NULL COMMENT '',
  `id_setor` INT(11) NULL COMMENT '',
  `id_cargo` INT(11) NULL COMMENT '',
  `id_pessoa` INT NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '',
  INDEX `id_setor` (`id_setor` ASC)  COMMENT '',
  INDEX `fk_Usuario_Cargo1` (`id_cargo` ASC)  COMMENT '',
  INDEX `id_pessoa_idx` (`id_pessoa` ASC)  COMMENT '',
  CONSTRAINT `fk_Usuario_Cargo1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `creas_db`.`cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `id_setor`
    FOREIGN KEY (`id_setor`)
    REFERENCES `creas_db`.`setor` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `id_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `creas_db`.`tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_tipo_relacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_tipo_relacao` (
  `id_tipo_relacao` INT NOT NULL COMMENT '',
  `nome_tipo_relacao` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_tipo_relacao`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_relacao_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_relacao_pessoa` (
  `id_pessoa` INT NOT NULL COMMENT '',
  `id_responsavel` INT NOT NULL COMMENT '',
  `id_relacao` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_pessoa`)  COMMENT '',
  INDEX `id_responsavel_idx` (`id_responsavel` ASC)  COMMENT '',
  INDEX `id_relacao_idx` (`id_relacao` ASC)  COMMENT '',
  CONSTRAINT `id_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `creas_db`.`tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_responsavel`
    FOREIGN KEY (`id_responsavel`)
    REFERENCES `creas_db`.`tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tipo_relacao`
    FOREIGN KEY (`id_relacao`)
    REFERENCES `creas_db`.`tb_tipo_relacao` (`id_tipo_relacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_tipo_habitacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_tipo_habitacional` (
  `id_tipo_habitacional` INT NOT NULL COMMENT '',
  `descricao_tipo_habitacional` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_tipo_habitacional`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_situacao_domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_situacao_domicilio` (
  `id_situacao_domicilio` INT NOT NULL COMMENT '',
  `descricao_situacao_domicilio` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_situacao_domicilio`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_sit_habitacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_sit_habitacional` (
  `id_sit_habitacional` INT NOT NULL COMMENT '',
  `id_tipo_habitacional` INT NOT NULL COMMENT '',
  `id_sit_domicilio` INT NULL COMMENT '',
  `tb_sit_habitacionalcol` VARCHAR(45) NULL COMMENT '',
  `tem_agua` TINYINT(1) NULL COMMENT '',
  `tem_esgoto` TINYINT(1) NULL COMMENT '',
  `tem_eletr` TINYINT(1) NULL COMMENT '',
  `tem_pavimento` TINYINT(1) NULL COMMENT '',
  `tem_coleta_lixo` TINYINT(1) NULL COMMENT '',
  `qtde_comodos_habitacao` INT NULL COMMENT '',
  `qtde_pessoas_habitacao` INT NULL COMMENT '',
  PRIMARY KEY (`id_sit_habitacional`)  COMMENT '',
  INDEX `id_tipo_habitacional_idx` (`id_tipo_habitacional` ASC)  COMMENT '',
  INDEX `id_sit_domicilio_idx` (`id_sit_domicilio` ASC)  COMMENT '',
  CONSTRAINT `id_tipo_habitacional`
    FOREIGN KEY (`id_tipo_habitacional`)
    REFERENCES `creas_db`.`tb_tipo_habitacional` (`id_tipo_habitacional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_sit_domicilio`
    FOREIGN KEY (`id_sit_domicilio`)
    REFERENCES `creas_db`.`tb_situacao_domicilio` (`id_situacao_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_endereco` (
  `id_endereco` INT NOT NULL COMMENT '',
  `id_localidade_endereco` INT NULL COMMENT '',
  `nome_localidade_endereco` TEXT NULL COMMENT '',
  `id_logradouro_endereco` INT NULL COMMENT '',
  `nome_logradouro_endereco` TEXT NULL COMMENT '',
  `complemento_endereco` TEXT NULL COMMENT '',
  `numero_endereco` INT NULL COMMENT '',
  `complemento_numero_endereco` TEXT NULL COMMENT '',
  `cep_endereco` INT NULL COMMENT '',
  `referencia_endereco` TEXT NULL COMMENT '',
  `id_sit_habitacional` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_endereco`)  COMMENT '',
  INDEX `fk_tb_endereco_tb_sit_habitacional1_idx` (`id_sit_habitacional` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_endereco_tb_sit_habitacional1`
    FOREIGN KEY (`id_sit_habitacional`)
    REFERENCES `creas_db`.`tb_sit_habitacional` (`id_sit_habitacional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_tipo_contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_tipo_contato` (
  `id_tipo_contato` INT NOT NULL COMMENT '',
  `descricao_tipo_contato` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_tipo_contato`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_contatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_contatos` (
  `id_contato` INT NOT NULL COMMENT '',
  `id_endereco` INT NOT NULL COMMENT '',
  `id_tipo_contato` INT NULL COMMENT '',
  `telefone_fixo_contato` INT NULL COMMENT '',
  `telefone_cel_contato` INT NULL COMMENT '',
  `email_contato` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_contato`, `id_endereco`)  COMMENT '',
  INDEX `fk_tb_contatos_tb_tipo_contato1_idx` (`id_tipo_contato` ASC)  COMMENT '',
  INDEX `fk_tb_contatos_tb_endereco1_idx` (`id_endereco` ASC)  COMMENT '',
  CONSTRAINT `id_tipo_contato`
    FOREIGN KEY (`id_tipo_contato`)
    REFERENCES `creas_db`.`tb_tipo_contato` (`id_tipo_contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_endereco`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `creas_db`.`tb_endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_pessoa_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_pessoa_endereco` (
  `id_pessoa` INT NOT NULL COMMENT '',
  `id_endereco` INT NULL COMMENT '',
  `endereco_principal` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id_pessoa`)  COMMENT '',
  INDEX `id_endereco_idx` (`id_endereco` ASC)  COMMENT '',
  CONSTRAINT `id_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `creas_db`.`tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_endereco`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `creas_db`.`tb_endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_cat_servico_socioass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_cat_servico_socioass` (
  `id_cat_servico_socioass` INT NOT NULL COMMENT '',
  `desc_cat_servico_socioasscol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_cat_servico_socioass`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_servico_socioass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_servico_socioass` (
  `id_servico_socioass` INT NOT NULL COMMENT '',
  `desc_servico_socioasscol` VARCHAR(45) NULL COMMENT '',
  `id_cat_servico_socioass` INT NULL COMMENT '',
  PRIMARY KEY (`id_servico_socioass`)  COMMENT '',
  INDEX `fk_tb_servico_socioass_1_idx` (`id_cat_servico_socioass` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_servico_socioass_1`
    FOREIGN KEY (`id_cat_servico_socioass`)
    REFERENCES `creas_db`.`tb_cat_servico_socioass` (`id_cat_servico_socioass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_servico_socioass_has_tb_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_servico_socioass_has_tb_pessoa` (
  `id_servico_socioass` INT NOT NULL COMMENT '',
  `id_pessoa` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_servico_socioass`, `id_pessoa`)  COMMENT '',
  INDEX `fk_tb_servico_socioass_has_tb_pessoa_tb_pessoa1_idx` (`id_pessoa` ASC)  COMMENT '',
  INDEX `fk_tb_servico_socioass_has_tb_pessoa_tb_servico_socioass1_idx` (`id_servico_socioass` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_servico_socioass_has_tb_pessoa_tb_servico_socioass1`
    FOREIGN KEY (`id_servico_socioass`)
    REFERENCES `creas_db`.`tb_servico_socioass` (`id_servico_socioass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_servico_socioass_has_tb_pessoa_tb_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `creas_db`.`tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_saude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_saude` (
  `id_tb_saude` INT NOT NULL COMMENT '	',
  `possui_cartao_sus` TINYINT(1) NULL COMMENT '',
  `num_cartao_sus` INT NULL COMMENT '',
  `frequenta_uni_saude` TINYINT(1) NULL COMMENT '',
  `consulta` TINYINT(1) NULL COMMENT '',
  `farmacia` TINYINT(1) NULL COMMENT '',
  `odontologia` TINYINT(1) NULL COMMENT '',
  `outros` TINYINT(1) NULL COMMENT '',
  `participa_saude_familia` TINYINT(1) NULL COMMENT '',
  `participa_atencao_sex` TINYINT(1) NULL COMMENT '',
  `adolescente_gravida` TINYINT(1) NULL COMMENT '',
  `acompanha_pre_natal` TINYINT(1) NULL COMMENT '',
  `deficiencia_fisica` TINYINT(1) NULL COMMENT '',
  `deficiencia_auditiva` TINYINT(1) NULL COMMENT '',
  `deficiencia_visual` TINYINT(1) NULL COMMENT '',
  `deficiencia_intelectual` TINYINT(1) NULL COMMENT '',
  `nenhuma_deficiencia` TINYINT(1) NULL COMMENT '',
  `remedio_uso_continuo` TINYINT(1) NULL COMMENT '',
  `qual_remedio` TEXT NULL COMMENT '',
  `usa_subs_psicoativas` TINYINT(1) NULL COMMENT '',
  `qual_substancia` TEXT NULL COMMENT '',
  `tratamento_CAPS_AD` INT NULL COMMENT '0 = não faz\n1 = faz\n2= já fez',
  `tratamento_CAPS` INT NULL COMMENT '0 = não faz\n1 = faz\n2= já fez',
  `tratamento_comun_terapeutica` INT NULL COMMENT '0 = não faz\n1 = faz\n2= já fez',
  `necessita_aval_tecnica` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id_tb_saude`)  COMMENT '',
  CONSTRAINT `fk_tb_saude_1`
    FOREIGN KEY (`id_tb_saude`)
    REFERENCES `creas_db`.`tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_unidade_saude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_unidade_saude` (
  `id_unid_saude` INT NOT NULL COMMENT '',
  `nome_unid_saude` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_unid_saude`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_unidade_saude_has_tb_saude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_unidade_saude_has_tb_saude` (
  `id_unid_saude` INT NOT NULL COMMENT '',
  `id_tb_saude` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_unid_saude`, `id_tb_saude`)  COMMENT '',
  INDEX `fk_tb_unidade_saude_has_tb_saude_tb_saude1_idx` (`id_tb_saude` ASC)  COMMENT '',
  INDEX `fk_tb_unidade_saude_has_tb_saude_tb_unidade_saude1_idx` (`id_unid_saude` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_unidade_saude_has_tb_saude_tb_unidade_saude1`
    FOREIGN KEY (`id_unid_saude`)
    REFERENCES `creas_db`.`tb_unidade_saude` (`id_unid_saude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_unidade_saude_has_tb_saude_tb_saude1`
    FOREIGN KEY (`id_tb_saude`)
    REFERENCES `creas_db`.`tb_saude` (`id_tb_saude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_trab_situacao_antes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_trab_situacao_antes` (
  `id_trab_situacao_antes` INT NOT NULL COMMENT '',
  `desc_trab_situacao_antes` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_trab_situacao_antes`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_trab_situacao_depois`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_trab_situacao_depois` (
  `id_trab_situacao_depois` INT NOT NULL COMMENT '',
  `desc_trab_situacao_depois` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_trab_situacao_depois`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_trabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_trabalho` (
  `id_trabalho` INT NOT NULL COMMENT '',
  `id_trab_situacao_antes` INT NULL COMMENT '',
  `id_trab_situacao_depois` INT NULL COMMENT '',
  `id_pessoa` INT NULL COMMENT '',
  PRIMARY KEY (`id_trabalho`)  COMMENT '',
  INDEX `fk_tb_trabalho_1_idx` (`id_trab_situacao_antes` ASC)  COMMENT '',
  INDEX `fk_tb_trabalho_2_idx` (`id_trab_situacao_depois` ASC)  COMMENT '',
  INDEX `fk_tb_trabalho_3_idx` (`id_pessoa` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_trabalho_1`
    FOREIGN KEY (`id_trab_situacao_antes`)
    REFERENCES `creas_db`.`tb_trab_situacao_antes` (`id_trab_situacao_antes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_trabalho_2`
    FOREIGN KEY (`id_trab_situacao_depois`)
    REFERENCES `creas_db`.`tb_trab_situacao_depois` (`id_trab_situacao_depois`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_trabalho_3`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `creas_db`.`tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_procedencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_procedencia` (
  `id_procedencia` INT NOT NULL COMMENT '',
  `nome_procedencia` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_procedencia`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_tipo_medidas_aplicadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_tipo_medidas_aplicadas` (
  `id_tipo_medidas_aplicadas` INT NOT NULL COMMENT '',
  `desc_tipo_medidas_aplicadas` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_tipo_medidas_aplicadas`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_situacao_processual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_situacao_processual` (
  `id_situacao_processual` INT NOT NULL COMMENT '',
  `id_pessoa` INT NULL COMMENT '',
  `id_procedencia` INT NULL COMMENT '',
  `vara` INT NULL COMMENT '',
  `mesmo_processo` TINYINT(1) NULL COMMENT '',
  `id_tipo_medidas_aplicadas` INT NULL COMMENT '',
  `id_medidas_aplicadas` INT NULL COMMENT '',
  PRIMARY KEY (`id_situacao_processual`)  COMMENT '',
  INDEX `fk_tb_situacao_processual_1_idx` (`id_pessoa` ASC)  COMMENT '',
  INDEX `fk_tb_situacao_processual_2_idx` (`id_procedencia` ASC)  COMMENT '',
  INDEX `fk_tb_situacao_processual_3_idx` (`id_tipo_medidas_aplicadas` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_situacao_processual_1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `creas_db`.`tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_situacao_processual_2`
    FOREIGN KEY (`id_procedencia`)
    REFERENCES `creas_db`.`tb_procedencia` (`id_procedencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_situacao_processual_3`
    FOREIGN KEY (`id_tipo_medidas_aplicadas`)
    REFERENCES `creas_db`.`tb_tipo_medidas_aplicadas` (`id_tipo_medidas_aplicadas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_infracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_infracao` (
  `id_infracao` INT NOT NULL COMMENT '',
  `desc_infracao` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_infracao`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_ato_infracional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_ato_infracional` (
  `id_ato_infracional` INT NOT NULL COMMENT '',
  `desc_ato_infracional` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_ato_infracional`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_medidas_aplicadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_medidas_aplicadas` (
  `id_medidas_aplicadas` INT NOT NULL COMMENT '',
  `id_situacao_processual` INT NULL COMMENT '',
  `num_processo` INT NULL COMMENT '',
  `num_execucao` INT NULL COMMENT '',
  `num_prontuario` INT NULL COMMENT '',
  `data_infracao` DATE NULL COMMENT '',
  `data_aplicacao_medida` DATE NULL COMMENT '',
  `prazo_determinado` INT NULL COMMENT '',
  `horas_semanais` INT NULL COMMENT '',
  `data_entrada_programa` DATE NULL COMMENT '',
  `id_infracao` INT NULL COMMENT '',
  `id_ato_infracional` INT NULL COMMENT '',
  `primeira_medida` TINYINT(1) NULL COMMENT '',
  `num_vezes` INT NULL COMMENT '',
  `cumulativa_psc` TINYINT(1) NULL COMMENT '',
  `cumprimento_integral_mse` TINYINT(1) NULL COMMENT '',
  `prazo_max_elaboracao_pia` DATE NULL COMMENT '',
  `data_fin_enc_pia` DATE NULL COMMENT '',
  `data_homolog_pia` DATE NULL COMMENT '',
  `previsao_termino_medida` DATE NULL COMMENT '',
  `data_enc_ultimo_relatorio` DATE NULL COMMENT '',
  `pedido_reavaliacao` TINYINT(1) NULL COMMENT '',
  `alteracao` TINYINT(1) NULL COMMENT '',
  `suspensao` TINYINT(1) NULL COMMENT '',
  `encerramento` TINYINT(1) NULL COMMENT '',
  `sol_por_adolescente` TINYINT(1) NULL COMMENT '',
  `sol_por_familia` TINYINT(1) NULL COMMENT '',
  `sol_por_diretor_programa` TINYINT(1) NULL COMMENT '',
  `sol_por_defensoria_publ` TINYINT(1) NULL COMMENT '',
  `sol_por_ministerio_publ` TINYINT(1) NULL COMMENT '',
  `pedido_reavaliacao_medida` TINYINT(1) NULL COMMENT '',
  `suspensao_temporaria_em` DATE NULL COMMENT '',
  `conclusao_medida_determinacao_jud` DATE NULL COMMENT '',
  `num_audiencias_acompanhadas_tecnico` INT NULL COMMENT '',
  PRIMARY KEY (`id_medidas_aplicadas`)  COMMENT '',
  INDEX `fk_tb_medidas_aplicadas_1_idx` (`id_situacao_processual` ASC)  COMMENT '',
  INDEX `fk_tb_medidas_aplicadas_2_idx` (`id_infracao` ASC)  COMMENT '',
  INDEX `fk_tb_medidas_aplicadas_3_idx` (`id_ato_infracional` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_medidas_aplicadas_1`
    FOREIGN KEY (`id_situacao_processual`)
    REFERENCES `creas_db`.`tb_situacao_processual` (`id_situacao_processual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_medidas_aplicadas_2`
    FOREIGN KEY (`id_infracao`)
    REFERENCES `creas_db`.`tb_infracao` (`id_infracao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_medidas_aplicadas_3`
    FOREIGN KEY (`id_ato_infracional`)
    REFERENCES `creas_db`.`tb_ato_infracional` (`id_ato_infracional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_encaminhamento_no_mes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_encaminhamento_no_mes` (
  `id_encaminhamento` INT NOT NULL COMMENT '',
  `nao_houve` TINYINT(1) NULL COMMENT '',
  `id_pessoa` INT NULL COMMENT '',
  PRIMARY KEY (`id_encaminhamento`)  COMMENT '',
  CONSTRAINT `fk_tb_encaminhamento_no_mes_1`
    FOREIGN KEY ()
    REFERENCES `creas_db`.`tb_pessoa` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_servicos_rede_socioassistencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_servicos_rede_socioassistencial` (
  `id_servico` INT NOT NULL COMMENT '',
  `nome_servico` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_servico`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_local_encaminhamento_PTR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_local_encaminhamento_PTR` (
  `id_local` INT NOT NULL COMMENT '',
  `nome_local` TEXT NULL COMMENT '',
  `id_encaminhamento` INT NULL COMMENT '',
  PRIMARY KEY (`id_local`)  COMMENT '',
  INDEX `fk_tb_local_encaminhamento_PTR_1_idx` (`id_encaminhamento` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_local_encaminhamento_PTR_1`
    FOREIGN KEY (`id_encaminhamento`)
    REFERENCES `creas_db`.`tb_encaminhamento_no_mes` (`id_encaminhamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_encaminhamento_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_encaminhamento_servicos` (
  `id_encaminhamento` INT NOT NULL COMMENT '',
  `id_servico` INT NULL COMMENT '',
  PRIMARY KEY (`id_encaminhamento`)  COMMENT '',
  INDEX `fk_tb_encaminhamento_servicos_2_idx` (`id_servico` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_encaminhamento_servicos_1`
    FOREIGN KEY (`id_encaminhamento`)
    REFERENCES `creas_db`.`tb_encaminhamento_no_mes` (`id_encaminhamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_encaminhamento_servicos_2`
    FOREIGN KEY (`id_servico`)
    REFERENCES `creas_db`.`tb_servicos_rede_socioassistencial` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_rede_ensino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_rede_ensino` (
  `id_rede_ensino` INT NOT NULL COMMENT '',
  `uf_` VARCHAR(2) NULL COMMENT '',
  `municipio` TEXT NULL COMMENT '',
  `nome_escola` TEXT NULL COMMENT '',
  `codigo_inep` INT NULL COMMENT '',
  `curso` TEXT NULL COMMENT '',
  `ano_serie` TEXT NULL COMMENT '',
  `vaga_negada` TINYINT(1) NULL COMMENT '',
  `id_encaminhamento` INT NULL COMMENT '',
  PRIMARY KEY (`id_rede_ensino`)  COMMENT '',
  INDEX `fk_tb_rede_ensino_1_idx` (`id_encaminhamento` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_rede_ensino_1`
    FOREIGN KEY (`id_encaminhamento`)
    REFERENCES `creas_db`.`tb_encaminhamento_no_mes` (`id_encaminhamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_atend_multidisciplinar_multissetorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_atend_multidisciplinar_multissetorial` (
  `id_atend` INT NOT NULL COMMENT '',
  `desc_atend` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_atend`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_sistema_saude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_sistema_saude` (
  `id_sistema_saude` INT NOT NULL COMMENT '',
  `nome_unid_saude` TEXT NULL COMMENT '',
  `vaga_negada` TINYINT(1) NULL COMMENT '',
  `caps_ad` INT NULL COMMENT '',
  `caps` INT NULL COMMENT '',
  `id_atendimento_multi` INT NULL COMMENT '',
  `adolescente_gravida` TINYINT(1) NULL COMMENT '',
  `id_encaminhamento` INT NULL COMMENT '',
  PRIMARY KEY (`id_sistema_saude`)  COMMENT '',
  INDEX `fk_tb_sistema_saude_1_idx` (`id_atendimento_multi` ASC)  COMMENT '',
  INDEX `fk_tb_sistema_saude_2_idx` (`id_encaminhamento` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_sistema_saude_1`
    FOREIGN KEY (`id_atendimento_multi`)
    REFERENCES `creas_db`.`tb_atend_multidisciplinar_multissetorial` (`id_atend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_sistema_saude_2`
    FOREIGN KEY (`id_encaminhamento`)
    REFERENCES `creas_db`.`tb_encaminhamento_no_mes` (`id_encaminhamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_programas_aprendizagem_sistema_S`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_programas_aprendizagem_sistema_S` (
  `id_programa_aprendizagem` INT NOT NULL COMMENT '',
  `desc_programa_aprendizagem` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_programa_aprendizagem`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_enc_outros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_enc_outros` (
  `id_enc_outros` INT NOT NULL COMMENT '',
  `oficinas_aprendizagem` TINYINT(1) NULL COMMENT '',
  `id_programa aprendizagem` INT NULL COMMENT '',
  `outro_programa` TEXT NULL COMMENT '',
  `insercao_mundo_trabalho` TINYINT(1) NULL COMMENT '',
  `programa_politica_habitacao` TINYINT(1) NULL COMMENT '',
  `oficinas_formacao_pessoal` TINYINT(1) NULL COMMENT '',
  `providencia_regul_documentos` TINYINT(1) NULL COMMENT '',
  `ativ_ludicas` TINYINT(1) NULL COMMENT '',
  `atividades_esporte_lazer_cultura` TINYINT(1) NULL COMMENT '',
  `ativ_convivencia_comunitaria` TINYINT(1) NULL COMMENT '',
  `acolhimento` TINYINT(1) NULL COMMENT '',
  `acolhimento_nome` TEXT NULL COMMENT '',
  `id_encaminhamento` INT NULL COMMENT '',
  PRIMARY KEY (`id_enc_outros`)  COMMENT '',
  INDEX `fk_tb_enc_outros_1_idx` (`id_encaminhamento` ASC)  COMMENT '',
  INDEX `fk_tb_enc_outros_2_idx` (`id_programa aprendizagem` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_enc_outros_1`
    FOREIGN KEY (`id_encaminhamento`)
    REFERENCES `creas_db`.`tb_encaminhamento_no_mes` (`id_encaminhamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_enc_outros_2`
    FOREIGN KEY (`id_programa aprendizagem`)
    REFERENCES `creas_db`.`tb_programas_aprendizagem_sistema_S` (`id_programa_aprendizagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_acompanhamento_mes_referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_acompanhamento_mes_referencia` (
  `id_acompanhamento_mes_referencia` INT NOT NULL COMMENT '',
  `id_pessoa` INT NOT NULL COMMENT '',
  `id_servico_socioass` INT NULL COMMENT '',
  `unidade_escolar` INT NULL COMMENT '0 = sem periodicidade\n1 = semanal\n2 = quinzenal\n3 =mensal',
  `caps_ad` INT NULL COMMENT '0 = sem periodicidade\n1 = semanal\n2 = quinzenal\n3 =mensal',
  `caps` INT NULL COMMENT '0 = sem periodicidade\n1 = semanal\n2 = quinzenal\n3 =mensal',
  `atendimento_multidisciplinar_multissetorial` INT NULL COMMENT '0 = sem periodicidade\n1 = semanal\n2 = quinzenal\n3 =mensal',
  `oficinas_aprendizagem` INT NULL COMMENT '0 = sem periodicidade\n1 = semanal\n2 = quinzenal\n3 =mensal',
  `programas_sistema_s` INT NULL COMMENT '0 = sem periodicidade\n1 = semanal\n2 = quinzenal\n3 =mensal',
  `insercao_mundo_trabalho` INT NULL COMMENT '0 = sem periodicidade\n1 = semanal\n2 = quinzenal\n3 =mensal',
  `oficinas_formacao_pessoal` INT NULL COMMENT '0 = sem periodicidade\n1 = semanal\n2 = quinzenal\n3 =mensal',
  `providencia_regul_documentos` INT NULL COMMENT '0 = sem periodicidade\n1 = semanal\n2 = quinzenal\n3 =mensal',
  `ativ_ludicas` INT NULL COMMENT '0 = sem periodicidade\n1 = semanal\n2 = quinzenal\n3 =mensal',
  `atividades_esporte_lazer_cultura` INT NULL COMMENT '0 = sem periodicidade\n1 = semanal\n2 = quinzenal\n3 =mensal',
  `ativ_convivencia_comunitaria` INT NULL COMMENT '0 = sem periodicidade\n1 = semanal\n2 = quinzenal\n3 =mensal',
  `servico_acolhimento_institucional` INT NULL COMMENT '0 = sem periodicidade\n1 = semanal\n2 = quinzenal\n3 =mensal',
  PRIMARY KEY (`id_acompanhamento_mes_referencia`)  COMMENT '',
  INDEX `fk_tb_acompanhamento_mes_referencia_1_idx` (`id_pessoa` ASC)  COMMENT '',
  INDEX `fk_tb_acompanhamento_mes_referencia_2_idx` (`id_servico_socioass` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_acompanhamento_mes_referencia_1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `creas_db`.`tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_acompanhamento_mes_referencia_2`
    FOREIGN KEY (`id_servico_socioass`)
    REFERENCES `creas_db`.`tb_servico_socioass` (`id_servico_socioass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_atendimento` (
  `id_atendimento` INT NOT NULL COMMENT '',
  `desc_atend` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_atendimento`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_acompanhamento_atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_acompanhamento_atendimento` (
  `id_acompanhamento_mes_referencia` INT NOT NULL COMMENT '',
  `id_atendimento` INT NULL COMMENT '',
  `data_acompanhamento` DATE NULL COMMENT '',
  PRIMARY KEY (`id_acompanhamento_mes_referencia`)  COMMENT '',
  INDEX `fk_tb_acompanhamento_atendimento_2_idx` (`id_atendimento` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_acompanhamento_atendimento_1`
    FOREIGN KEY (`id_acompanhamento_mes_referencia`)
    REFERENCES `creas_db`.`tb_acompanhamento_mes_referencia` (`id_acompanhamento_mes_referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_acompanhamento_atendimento_2`
    FOREIGN KEY (`id_atendimento`)
    REFERENCES `creas_db`.`tb_atendimento` (`id_atendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_tipo_visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_tipo_visita` (
  `id_tipo_visita` INT NOT NULL COMMENT '',
  `desc_tipo_visita` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_tipo_visita`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creas_db`.`tb_acompanhamento_visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creas_db`.`tb_acompanhamento_visitas` (
  `id_acompanhamento_mes_referencia` INT NOT NULL COMMENT '',
  `id_tipo_visita` INT NULL COMMENT '',
  `data_visita` DATE NULL COMMENT '',
  PRIMARY KEY (`id_acompanhamento_mes_referencia`)  COMMENT '',
  INDEX `fk_tb_acompanhamento_visitas_1_idx` (`id_tipo_visita` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_acompanhamento_visitas_1`
    FOREIGN KEY (`id_tipo_visita`)
    REFERENCES `creas_db`.`tb_tipo_visita` (`id_tipo_visita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_acompanhamento_visitas_2`
    FOREIGN KEY (`id_acompanhamento_mes_referencia`)
    REFERENCES `creas_db`.`tb_acompanhamento_mes_referencia` (`id_acompanhamento_mes_referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
